use_frameworks!
platform :ios, '10.0'

target 'Swifty_Example' do
  pod 'Swifty', :path => '../'

  target 'Swifty_Tests' do
  	pod 'Alamofire', '~> 5.0.0-beta.6'
    inherit! :search_paths
    
  end
end
